# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "add_workflow-1" ]
  pull_request:
    branches: [ "add_workflow-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
          sudo apt update
          sudo apt install -y cmake build-essential liblapack-dev libblas-dev
    - name: Build Linux
      run: >
        mkdir build;
        cd build;
        cmake ../ ;
        make

    - name: Test
      working-directory: build
      run: ctest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: shared-artifact
          path: bin/
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4\
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: bin/
    - name: List downloaded artifacts
      run: ls -l bin/*
    - name: Run --help for all files in bin/
      run: |
          echo "Running --help for all files in bin/"
          for file in bin/*; do
            if [[ -x "$file" ]]; then
              echo "----- $file --help -----"
              "$file" --help || echo "$file failed"
              echo
            else
              echo "Skipping non-executable $file"
            fi
          done
        
