# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - '**'  # Matches all branches

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
          sudo apt update
          sudo apt install -y cmake build-essential liblapack-dev libblas-dev
    - name: Build
      run: >
        mkdir build;
        cd build;
        cmake ../ ;
        make

    - name: Test
      working-directory: build
      run: ctest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: shared-artifact-linux
          path: |
            bin/ 
            lib/librtklib.so
  test_linux:
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: shared-artifact-linux
    - name: List downloaded artifacts
      run: ls -l bin/*
    - name: Prepare environment
      run: sudo cp lib/librtklib.so /usr/local/lib/; sudo ldconfig
    - name: Make bin files executable
      run: chmod +x bin/*
    - name: Run --help for all files in bin/
      run: |
          echo "Running --help for all files in bin/"
          for file in bin/*; do
            if [[ -x "$file" ]]; then
              echo "----- $file --help -----"
              "$file" --help || echo "$file failed"
              echo
            else
              echo "Skipping non-executable $file"
            fi
          done
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
    - name: Install shell-like env
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-openblas
    - name: Add ln
      shell: msys2 {0}
      run: |
          cd /mingw64/lib
          cp /mingw64/lib/libopenblas.dll.a /mingw64/lib/libblas.a
          cp /mingw64/lib/libopenblas.dll.a /mingw64/lib/liblapack.a
    - name: Build
      shell: cmd
      run: |
        where gcc
        mkdir build
        cd build
        pwd
        cmake .. -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ cmake .. -G"MinGW Makefiles" -DCMAKE_EXE_LINKER_FLAGS="-LD:/a/_temp/msys64/mingw64/lib -lwinmm" 
        cmake --build .
    - name: Test
      working-directory: build
      run: ctest -C Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: shared-artifact-windows
          path: |
            build/bin/
            build/Release/